"""Starting-point instruments. Use as instrument="preset:<name>" or copy and edit."""

PRESETS = {
    "saw_lead": {"type": "synth", "oscs": [{"wave": "saw", "unison": 3, "detune": 12}],
                 "filter": {"type": "lp24", "cutoff": 4000, "res": 0.2, "env_amount": 1.5},
                 "amp_env": {"a": 0.005, "d": 0.3, "s": 0.8, "r": 0.1}},
    "supersaw": {"type": "synth", "oscs": [{"wave": "saw", "unison": 7, "detune": 25, "spread": 0.9}],
                 "filter": {"type": "lp12", "cutoff": 9000, "res": 0.1},
                 "amp_env": {"a": 0.01, "d": 0.5, "s": 0.9, "r": 0.3}},
    "square_lead": {"type": "synth", "oscs": [{"wave": "square", "pw": 0.35}],
                    "filter": {"type": "lp24", "cutoff": 3000, "res": 0.3, "env_amount": 1.0},
                    "amp_env": {"a": 0.003, "d": 0.2, "s": 0.7, "r": 0.08}},
    "sub_bass": {"type": "synth", "oscs": [{"wave": "sine"}], "mono": True, "glide": 0.02,
                 "amp_env": {"a": 0.003, "d": 0.1, "s": 1.0, "r": 0.04}},
    "acid_bass": {"type": "synth", "oscs": [{"wave": "saw"}], "mono": True, "glide": 0.06,
                  "filter": {"type": "ladder", "cutoff": 400, "res": 0.75, "env_amount": 3.0, "drive": 2.0},
                  "filter_env": {"a": 0.001, "d": 0.18, "s": 0.0, "r": 0.05},
                  "amp_env": {"a": 0.002, "d": 0.2, "s": 0.8, "r": 0.03}},
    "reese_bass": {"type": "synth", "oscs": [{"wave": "saw", "unison": 2, "detune": 18, "spread": 0.3},
                                            {"wave": "sine", "octave": -1, "level": 0.6}],
                   "filter": {"type": "lp24", "cutoff": 700, "res": 0.15}, "mono": True, "glide": 0.03,
                   "drive": 6, "amp_env": {"a": 0.005, "d": 0.2, "s": 1.0, "r": 0.06}},
    "distorted_bass": {"type": "synth", "oscs": [{"wave": "saw"}, {"wave": "square", "octave": -1, "level": 0.7}],
                       "drive": 18, "filter": {"type": "lp24", "cutoff": 1800, "res": 0.3, "env_amount": 1.5},
                       "filter_env": {"a": 0.001, "d": 0.25, "s": 0.3, "r": 0.1}, "mono": True,
                       "amp_env": {"a": 0.002, "d": 0.2, "s": 1.0, "r": 0.05}},
    "pluck": {"type": "synth", "oscs": [{"wave": "saw", "unison": 2, "detune": 8}],
              "filter": {"type": "lp24", "cutoff": 500, "res": 0.2, "env_amount": 4.0},
              "filter_env": {"a": 0.001, "d": 0.15, "s": 0.0, "r": 0.1},
              "amp_env": {"a": 0.001, "d": 0.35, "s": 0.0, "r": 0.2}},
    "pad": {"type": "synth", "oscs": [{"wave": "saw", "unison": 5, "detune": 18, "spread": 0.9},
                                     {"wave": "triangle", "octave": 1, "level": 0.3}],
            "filter": {"type": "lp12", "cutoff": 2500, "res": 0.1},
            "amp_env": {"a": 0.6, "d": 1.0, "s": 0.8, "r": 1.2},
            "lfos": [{"target": "cutoff", "rate": 0.2, "depth": 0.5}]},
    "organ": {"type": "synth", "oscs": [{"wave": "additive", "partials": [1, 0.8, 0.6, 0.5, 0, 0.3, 0, 0.25]}],
              "amp_env": {"a": 0.005, "d": 0.1, "s": 1.0, "r": 0.05}},
    "fm_bell": {"type": "synth", "oscs": [{"wave": "sine", "semi": 19, "fine": 5, "level": 0.0},
                                         {"wave": "sine", "fm_from": 0, "fm_amount": 1.2}],
                "amp_env": {"a": 0.001, "d": 1.5, "s": 0.0, "r": 1.0}},
    "fm_bass": {"type": "synth", "oscs": [{"wave": "sine", "level": 0.0}, {"wave": "sine", "fm_from": 0, "fm_amount": 0.8}],
                "mono": True, "amp_env": {"a": 0.002, "d": 0.3, "s": 0.7, "r": 0.05},
                "lfos": [{"target": "fm", "rate_beats": 0.5, "depth": 0.5, "shape": "triangle"}]},
    "noise_riser": {"type": "synth", "oscs": [{"wave": "saw", "level": 0.0}], "noise": 1.0,
                    "filter": {"type": "bp", "cutoff": 400, "res": 0.4, "env_amount": 5.0},
                    "filter_env": {"a": 4.0, "d": 0.1, "s": 1.0, "r": 0.3},
                    "amp_env": {"a": 3.0, "d": 0.1, "s": 1.0, "r": 0.3}},
    "kick": {"type": "kick"},
    "kick_hard": {"type": "kick", "pitch_start": 220, "pitch_end": 50, "pitch_decay": 0.03, "decay": 0.35,
                  "click": 0.5, "drive": 8},
    "snare": {"type": "snare"},
    "clap": {"type": "clap"},
    "hat_closed": {"type": "hat", "decay": 0.04},
    "hat_open": {"type": "hat", "decay": 0.25},
    "kit_basic": {"type": "kit", "map": {"C1": {"type": "kick"}, "D1": {"type": "snare"}, "D#1": {"type": "clap"},
                                         "F#1": {"type": "hat", "decay": 0.04}, "A#1": {"type": "hat", "decay": 0.25}}},
}

GM_DRUMS = {"kick": "C1", "snare": "D1", "clap": "D#1", "hat": "F#1", "open_hat": "A#1", "tom_low": "A1",
            "tom_high": "D2", "crash": "C#2", "ride": "D#2"}
