"""Vinyl-style surface noise, designed (no recording): sparse clicks of random size and width plus a soft band-passed
hiss, wide stereo. Generated by absolute song time (one generator per 100 ms block, seeded by the block's song
number), so any window renders as the whole song does. A note turns it on for its length at its velocity."""
import numpy as np

INFO = {
    "summary": "designed vinyl surface noise: clicks + hiss, by song time",
    "range": "any pitch (ignored)",
    "velocity": "level",
    "params": {"clicks_per_s": "mean click rate", "hiss_db": "hiss level re clicks", "level": "output gain"},
    "source": "designed",
}


def perform(notes, total_n, sr, bpm=120.0, lanes=None, beat0=0.0, clicks_per_s=6.0, hiss_db=-14.0, level=1.0, **_):
    from scipy import signal
    t0 = beat0 * 60.0 / bpm
    gate = np.zeros(total_n)
    for st, m, d, v in notes:
        a = max(0, int(st * sr))
        b = min(total_n, int((st + d) * sr))
        gate[a:b] = np.maximum(gate[a:b], v / 127.0)
    if not gate.any():
        return np.zeros((2, total_n))
    blk = int(0.1 * sr)
    first = int(np.floor(t0 / 0.1))
    n_blk = total_n // blk + 2
    out = np.zeros((2, (n_blk + 1) * blk))
    off = int(round((t0 - first * 0.1) * sr))
    for k in range(n_blk):
        r = np.random.default_rng([first + k + 100000, 7])
        base = k * blk
        h = r.normal(0, 1, (2, blk))
        out[:, base:base + blk] += h * 10 ** (hiss_db / 20) * 0.05
        for _ in range(r.poisson(clicks_per_s * 0.1)):
            p = base + int(r.integers(0, blk))
            w = int(r.integers(2, 24))
            amp = r.lognormal(-2.2, 0.8)
            c = r.normal(0, 1, w) * np.hanning(w) * amp
            ch = r.integers(0, 3)
            if ch != 1:
                out[0, p:p + w] += c[: max(0, min(w, out.shape[1] - p))]
            if ch != 0:
                out[1, p:p + w] += c[: max(0, min(w, out.shape[1] - p))] * 0.9
    out = out[:, off:off + total_n]
    b, a = signal.butter(2, [300 / (sr / 2), 9000 / (sr / 2)], 'band')
    out = signal.lfilter(b, a, out, axis=1)
    return out * gate * level
